### ISSUE TITLE
Update bower.json when releasing a new version

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-tools#29]
Modify `slt-release` to detect `bower.json` in the project root and update the version field in that file when making a new release.

**Comment by ritch** [comment]
This would be pretty cool...

So to be clear to release to bower you just need to update the version field? I'm assuming you need some sort of committed distributable then ... boooooo :(

**Comment by bajtos** [comment]
> So to be clear to release to bower you just need to update the version field? I'm assuming you need some sort of committed distributable then

Ah, that's true. Bower installs from git(hub) named tags, if I read their [docs](http://bower.io/docs/creating-packages/#register) correctly: 

> - Your package should use semver Git tags.
> - Your package must be publically available at a Git endpoint (e.g., GitHub). Remember to push your Git tags!

Here is a possible solution:
 1) Extend `slt-release` to run `npm run prerelease` before committing the version changes and commit any files generated by this command
 2) Implement a "prerelease" script in angular-live-set, this script should build all distributables as needed

This will store the autogenerated distributables in the tag commits only,  keeping the master clean.

Thoughts?

**Comment by rmg** [comment]
This was added in #37
