### ISSUE TITLE
Update README.md with `slt license` usage docs

### ISSUE THREAD

**Issue by superkhau** [strongloop/strong-tools#33]
I would like to use `slt license` to ensure LB example repos are update to snuff with regards to licensing. At the moment, typing in `slt license` with the latest `strongloop` only shows:

```
Usage: slt <CMD> [PKG]

Commands:
  lint        Perform a simple linting of the given package.json
  cla         Create or verify contribution guidelines
  license     Set package licensing
  info        Display metadata about package
  version     Version manipulation
  semver      Wrapper for semver command from semver package
  help        Print this usage guide

Confirm license changes are acceptable with:
    git diff -M --cached -w --ignore-blank-lines
```

It doesn't actually set any licensing or create any LICENSE files, etc. Please advise on what to do.

**Comment by superkhau** [comment]
Waiting for https://github.com/strongloop/strong-tools/pull/32 to merge according to @sam-github

**Comment by rmg** [comment]
The reason `slt license` didn't work (at all) is because that particular command depends on node v0.12 or newer: b3a1d0109ccf90981c166a3063ddb9510822cab9

**Comment by sam-github** [comment]
closing via https://github.com/strongloop/strong-tools/pull/32
