### ISSUE TITLE
Distributed packages include too many files

### ISSUE THREAD

**Issue by eddiemonge** [strongloop/strong-tools#71]
By including files that the distributed package does not need, these negative side effects occur:
 - Installs take longer because unneeded files are downloaded
 - Installed packages take up more disk space

**Comment by sam-github** [comment]
@eddiemonge distributed packages of what? What files? Are you talking about the strong-tools package, or the packages published by slt-release?

**Comment by eddiemonge** [comment]
I'm talking about all of our npm modules. We are including too many files in all of them. It also causes things like https://github.com/strongloop/strong-tools/issues/70

**Comment by sam-github** [comment]
@eddiemonge please list the things you think strong-tools can automatically not include, otherwise this is not actionable.

And I want to point out that tiny config files, like .eslintrc, have no measurable impact on package size.

Particularly when put along side the ludicrously large legal notices we are putting into all the packages, those might be close to 20% of the on disk size of apiconnect, IIRC.

**Comment by eddiemonge** [comment]
Ideally I'd like to see it only include 

- index.js
- license files (for the lawyers)
- lib
- bin

**Comment by sam-github** [comment]
@eddiemonge you have no idea if that is all that needs to be published (cf. https://github.com/strongloop/strong-mesh-models, which needs client, common, server), or the names of the license files, and there is little evidence that the size of the packages is making install slow (as opposed to the sheer number of deps).

Note that every package explicitly controls what they publish via .npmignore.

**Comment by bajtos** [comment]
> Note that every package explicitly controls what they publish via .npmignore.

FWIW, one can also configure a white-list of files to include in the tarball via `files` in `package.json`, see https://docs.npmjs.com/files/package.json#files.

I personally agree with @sam-github that it's the responsibility of each package to decide which files are required in the published tarball.
