### ISSUE TITLE
slt-release should update the version in npm.shrinkwrap.json

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strong-tools#83]
Right now, when we generate the shrinkwrap file, it is based on the current version of the package.json,  However, when we slt-release  , it automatically pumped up the package.json and publish a new version, However. the version number in npm-shrinkwrap.json is behind, can we sync up the version as the package.json?

**Comment by rmg** [comment]
@smartmouse this is addressed in v5.2.0 which was just published :-)
